CREATE TABLE IF NOT EXISTS DB1 (
  id  INT PRIMARY KEY,
  V1  VARCHAR(20),
  V2  VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS DB2 (
  id  INT PRIMARY KEY,
  V1  VARCHAR(20),
  V2  VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS DB3 (
  id  INT PRIMARY KEY,
  V1  VARCHAR(20),
  V2  VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS DB4 (
  id  INT PRIMARY KEY,
  V1  VARCHAR(20),
  V2  VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS DB5 (
  id  INT PRIMARY KEY,
  V1  VARCHAR(20),
  V2  VARCHAR(20)
);

DROP TABLE IF EXISTS DB;

CREATE TABLE IF NOT EXISTS DB (
  id  INT PRIMARY KEY
);